export function mapPembiayaan(item, includeCabang = false) {
  return {
    kode: item.KODE,
    ...(includeCabang ? { kdcab: item.KDCAB } : {}),
    nodealer: item.NODEALER,
    nmdealer: item.NMDEALER,
    nmdebitur: item.NMDEBITUR,
    nou: item.NOU,
    outstanding: item.OUTSTANDING,
    jthtempomou: item.JTHTEMPOMOU,
    plafond: item.PLAFOND,
    plfsisa: item.PLFSISA,
    baserate: item.BASERATE,
    marketing: item.MARKETING.length > 1 ? item.MARKETING[0] : item.MARKETING,
    tgltrn: item.TGLTRN,
    jnsproduk: item.JNSPRODUK,
    jnskend: item.JNSKEND,
    merkkend: item.MERKKEND,
    tipekend: item.TIPEKEND,
    warna: item.WARNA,
    thnbuat: item.THNBUAT,
    nopol: item.NOPOL,
    nobpkb: item.NOBPKB,
    odometer: item.ODOMETER,
    konkend: item.KONKEND,
    bpkbflg: item.BPKBFLG !== '0',
    faktura: item.FAKTURA,
    fakturc: item.FAKTURC,
    ktpflg: item.KTPFLG !== '0',
    nikflg: item.NIKFLG !== '0',
    stnkflg: item.STNKFLG !== '0',
    kwitansiflg: item.KWITANSIFLG !== '0',
    nokanosin: item.NOKANOSIN,
    ketpbd: item.KETPBD,
    kodeao: item.KODEAO,
    nlpasar: item.NLPASAR,
    nominal: item.NOMINAL,
    persen: item.PERSEN,
    sphflg: item.SPHFLG !== '0',
    kwjbflg: item.KWJBFLG !== '0',
  }
}